# Generated by Django 3.0.8 on 2020-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200711_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='stage',
            field=models.IntegerField(choices=[(1, '参赛'), (2, '为参赛'), (0, '待定')], default=0, verbose_name='参赛状态'),
        ),
    ]
