# Generated by Django 3.0.8 on 2020-07-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=300, verbose_name='邮箱'),
        ),
    ]
