# Generated by Django 3.0.8 on 2020-07-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userinfo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='photo',
        ),
    ]
