# Generated by Django 3.0.8 on 2020-07-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='照片'),
        ),
    ]
