# Generated by Django 3.0.8 on 2020-07-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200719_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, '参赛'), (2, '未参赛'), (0, '待定')], verbose_name='参赛状态'),
        ),
    ]
