# Generated by Django 3.0.8 on 2020-07-22 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200722_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 13, 55, 39, 185715, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
