# Generated by Django 3.0.8 on 2020-07-25 05:51

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20200722_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-updated',), 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AddField(
            model_name='articlepost',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='articles_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 5, 51, 32, 759195, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
