# Generated by Django 3.0.8 on 2020-07-27 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200727_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 14, 22, 45, 188825, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
